# Auto-generated by the ellipsis-dev/cli release workflow. Do not edit by hand.
class Agent < Formula
  desc "Ellipsis agent CLI — drive the Ellipsis cloud from your terminal"
  homepage "https://ellipsis.dev"
  version "0.8.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.8.3/agent-darwin-arm64.tar.gz"
      sha256 "68a26733aaa2e80081ecfa771ef6d00d259f78b6acc9e32c85f0a5de0a72163a"
    end
    on_intel do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.8.3/agent-darwin-x64.tar.gz"
      sha256 "b441cfb47212081927b903414b72da273a049110afeeda7a402805d0de1c26ca"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.8.3/agent-linux-arm64.tar.gz"
      sha256 "2c8a262ba081ec93e1e3a5efc06f48795733642096541fa0a21469ada8cfd04a"
    end
    on_intel do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.8.3/agent-linux-x64.tar.gz"
      sha256 "3f0d42f72dbf54e30bf09ae3ce819243b4c156600e5c63d78640b9b4c6bc443a"
    end
  end

  def install
    bin.install "agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent --version")
  end
end
