# Auto-generated by the ellipsis-dev/cli release workflow. Do not edit by hand.
class Agent < Formula
  desc "Ellipsis agent CLI — drive the Ellipsis cloud from your terminal"
  homepage "https://ellipsis.dev"
  version "0.13.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.13.0/agent-darwin-arm64.tar.gz"
      sha256 "bf9fd9ce8e69a554eb61fd8e4cc799212460f5a0667a17d2da93f79926eeee9a"
    end
    on_intel do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.13.0/agent-darwin-x64.tar.gz"
      sha256 "e16cc3789269ae81ca3fcd632e10045575df6f50cefe9011b20d059e7121caa3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.13.0/agent-linux-arm64.tar.gz"
      sha256 "47748ebe8ee78f43da0422f22d4e31fb2609aa902981099422ebc93abc8965fe"
    end
    on_intel do
      url "https://github.com/ellipsis-dev/cli/releases/download/v0.13.0/agent-linux-x64.tar.gz"
      sha256 "379eda8179c02869b1d84ba1a4505d4e256f32d99e29e7923f9e6735b20ac906"
    end
  end

  def install
    bin.install "agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent --version")
  end
end
